# Generated by Django 4.1.2 on 2023-01-25 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64)),
                ('ttl_minutes', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
            ],
            options={
                'db_table': 'dish_reservations',
            },
        ),
        migrations.CreateModel(
            name='DishDailyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('available_count', models.IntegerField()),
                ('revision', models.IntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
            ],
            options={
                'db_table': 'dish_daily_availabilities',
            },
        ),
    ]
